### ISSUE TITLE
Release and deployment checklist 0.14.0

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#205]
Here is the immediate TODO list for the current release 0.14.0 of anaconda-build:

 * [x] Make win-64, win-32, linux-64, linux-32, osx-64 conda packages for (Edit 2/12/2016: I actually made pip / pypi installs rather than conda installs because of [conda build issue 713](https://github.com/conda/conda-build/issues/713)):
  * [x] chalmers (no PRs to merge, just build package for 0.7.8)
  * [x] anaconda-build. First merge PRs:
    * [x] #201 
    * [x] #202 
    * [x] #203
  * [x] clyent
    * [x] Merge PR #2
  * [x] anaconda-client [DEFERRED]
    * [x] @srossross @stephenakearns are there any anaconda-client PR's that must go into the curent deploy of anaconda-build workers?
 * [x] Follow the windows deploy instructions in #198, based on deploying and modifying ami's that already have visual studio.  Do that for 32-bit and 64-bit windows.
 * [x] Run windows update on all windows
 * [x] For the linux and osx workers, do not start from fresh ami's but rather conda install the new packages above, as well as other dependencies described in the wiki documentation.
 * [x] Build a new docker image, based on PR #203, for the purpose of:
  * [x] Updating conda-build
  * [x] Updating for the new packages above
  * [x] Installing subversion

(docker is used on the linux binstar/public queue workers where at least a conda-build update is needed now)

**Comment by PeterDSteinberg** [comment]
Other items that were completed on 2/11/2016:
 * Created Windows 32- and 64-bit AMI's of the anaconda-build 0.14.0 set up with 2 minicondas, updated visual studio, and all dependencies

Remaining TODO list as of 2/12/2016:

 * [ ] Make conda packages for chalmers, clyent, anaconda-build after resolution of [conda build 713](https://github.com/conda/conda-build/issues/713)
 * [ ] Update docker image after the item above (docker image installs via conda not pip for these)

**Comment by PeterDSteinberg** [comment]
Closing this issue as completed in OK status.
