### ISSUE TITLE
Release / Deploy for Milestone 0.15.0

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-build#250]
Checklist for release of milestone 0.15.0 (which may not be called 0.15.0 with the new platform versioning system):

#### Anaconda-build milestone 0.15.0 activities
 * [ ] Review and merge #245 
 * [ ] Address or partially issue #244 
 * [ ] More discussion and planning around #223 
 * [ ] Discuss plan for better osx-64 performance (add worker(s) and/or SSD)
 * [ ] Finish docker related PR with anaconda-cluster: https://github.com/ContinuumIO/anaconda-cluster-contrib/pull/15 . 

#### Release / deploy process
 * [ ] Release new `salt-anaconda-builder` package in `anaconda-cluster` channel (after PR 15 is merged there)
 * [ ] Update `CHANGELOG.txt` for this and several recent versions (out-of-date already)
 * [ ] Tag branch and merge develop into master
 * [ ] Contact Ilan to build and release `anaconda-build` (no updates to other relevant packages like `chalmers`)
 * [ ] Build and push the docker image for `binstar/linux-64` without using the local docker cache.  Push two images:
   * [ ] `binstar/linux-64:latest`
   * [ ] `binstar/linux-64:0.15.0` (replacing 0.15.0 with what we name this version)
 * [ ] On each machine, update conda conda-build anaconda-client anaconda-build pip (as root and binstar users separately on Windows)
 * [ ] On Windows machines, do Windows update and restart, but FIRST check to see if there is a startup file for chalmers that may be out of date regarding the chalmers command to run at startup
 * [ ] On all machines, make sure the env variable CC is set in chalmers, e.g., `chalmers set anaconda-build-worker CC=gcc`
 * [ ] `chalmers restart --all` on all workers
 * [ ] trigger builds to test it out
